-- ============================================
-- Seeder: Accessories (SQLite Compatible)
-- ============================================

-- Reset accessories so the new data seeds clean
DELETE FROM accessories;

-- Insert seeded accessories with pricing, availability, and discount links
INSERT INTO accessories (
  code,
  name,
  description,
  purchase_price,
  rental_price_per_day,
  sale_price,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  image_path,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  discount_group_id,
  created_at,
  updated_at
) VALUES
  (
    'AC001',
    'Tiara Emas Klasik',
    'Tiara beraksen emas untuk pengantin wanita, cocok dipadukan dengan kebaya tradisional.',
    180000,
    45000,
    420000,
    4,
    4,
    1,
    'images/accessories/tiara-emas.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'A'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'AC002',
    'Syal Batik Mega Mendung',
    'Syal sutra dengan motif megamendung untuk memperkaya tampilan foto pre-wedding.',
    22000,
    8000,
    60000,
    12,
    12,
    2,
    'images/accessories/syal-batik.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'B'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'AC003',
    'Gelang Perak Motif Klasik',
    'Gelang perak dengan detail ukiran tradisional untuk menambah estetika pakaian adat.',
    35000,
    10000,
    110000,
    8,
    7,
    1,
    'images/accessories/gelang-perak.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'C'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'AC004',
    'Tas Nasional',
    'Tas rajut etnik dari bahan alam yang bisa menjadi tambahan praktis untuk penyimpanan properti.',
    42000,
    12000,
    125000,
    6,
    6,
    1,
    'images/accessories/tas-nasional.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'D'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
  -- Additional accessories for richer master data
  INSERT INTO accessories (
    code,
    name,
    description,
    purchase_price,
    rental_price_per_day,
    sale_price,
    stock_quantity,
    available_quantity,
    min_stock_alert,
    image_path,
    is_available_for_rent,
    is_available_for_sale,
    is_active,
    discount_group_id,
    created_at,
    updated_at
  ) VALUES
    (
      'AC005',
      'Kipas Anyaman Etnik',
      'Kipas anyaman dari rotan dengan motif tradisional, cocok untuk properti foto dan event.',
      15000,
      5000,
      42000,
      20,
      20,
      3,
      'images/accessories/kipas-anyaman.jpg',
      1,
      1,
      1,
      (SELECT id FROM discount_groups WHERE code = 'I'),
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    ),
    (
      'AC006',
      'Sepatu Pengantin Klasik',
      'Sepatu hak rendah beraksen emas untuk dipadukan dengan kebaya pengantin Jawa.',
      75000,
      22000,
      250000,
      5,
      5,
      1,
      'images/accessories/sepatu-pengantin.jpg',
      1,
      1,
      1,
      (SELECT id FROM discount_groups WHERE code = 'J'),
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    ),
    (
      'AC007',
      'Bros Kaca Kristal',
      'Bros vintage dengan kristal untuk memberi aksen elegan pada jas atau kebaya.',
      32000,
      9000,
      95000,
      9,
      8,
      1,
      'images/accessories/bros-kristal.jpg',
      1,
      1,
      1,
      (SELECT id FROM discount_groups WHERE code = 'A'),
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    );
