-- ============================================
-- Seeder: Items (SQLite Compatible)
-- ============================================

-- Insert default items
INSERT INTO items (
  code,
  name,
  category_id,
  description,
  purchase_price,
  rental_price_per_day,
  sale_price,
  price,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  image_path,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  type,
  status,
  size_id
)
VALUES
  (
    'ITM-ADAT-001',
    'Kebaya Batik Pekalongan',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    'Kebaya tradisional dengan bordir tangan khas Pekalongan.',
    450.00,
    95.00,
    0.00,
    95.00,
    3,
    3,
    1,
    NULL,
    1,
    0,
    1,
    'RENTAL',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-M')
  ),
  (
    'ITM-ADAT-002',
    'Baju Adat Bali',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    'Kostum adat Bali menggunakan tenun songket dan renda emas.',
    520.00,
    105.00,
    0.00,
    105.00,
    2,
    2,
    1,
    NULL,
    1,
    0,
    1,
    'RENTAL',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-L')
  ),
  (
    'ITM-PER-001',
    'Gaun Pengantin Putih',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    'Gaun pengantin putih dengan ekor cathedral dan detail kristal.',
    1300.00,
    220.00,
    2800.00,
    2800.00,
    2,
    2,
    1,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-FREE')
  ),
  (
    'ITM-PER-002',
    'Set Jas Pengantin Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    'Set jas slim-fit dan rompi dengan aksesori kain satin.',
    800.00,
    160.00,
    2100.00,
    2100.00,
    3,
    3,
    1,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-M')
  ),
  (
    'ITM-ACF-001',
    'Evening Gown Ruby',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    'Gown pesta merah delima dengan detail drapery modern.',
    600.00,
    85.00,
    0.00,
    85.00,
    3,
    3,
    1,
    NULL,
    1,
    0,
    1,
    'RENTAL',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-L')
  ),
  (
    'ITM-ACF-002',
    'Tuxedo Midnight',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    'Tuxedo hitam dengan satin shawl lapel untuk jamuan malam.',
    550.00,
    70.00,
    1250.00,
    1250.00,
    4,
    4,
    1,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-M')
  ),
  (
    'ITM-ANK-001',
    'Gaun Anak Putri',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak'),
    'Gaun anak polos dengan layer tule dan pita besar.',
    220.00,
    45.00,
    420.00,
    420.00,
    6,
    6,
    2,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-KIDS')
  ),
  (
    'ITM-CRM-001',
    'Set Batik Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern'),
    'Set atasan dan rok batik eco print untuk street style.',
    340.00,
    60.00,
    700.00,
    700.00,
    5,
    5,
    1,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-L')
  ),
  (
    'ITM-ACC-001',
    'Mahkota Kristal Emas',
    (SELECT id FROM categories WHERE name = 'Aksesoris'),
    'Mahkota emas berhiaskan kristal Swarovski untuk foto prewedding.',
    180.00,
    35.00,
    420.00,
    420.00,
    7,
    7,
    2,
    NULL,
    1,
    1,
    1,
    'HYBRID',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-FREE')
  ),
  (
    'ITM-SUP-001',
    'Box Kostum Premium',
    (SELECT id FROM categories WHERE name = 'Peralatan Pendukung'),
    'Box penyimpanan custom dengan alas busa untuk menjaga kostum.',
    80.00,
    12.00,
    0.00,
    12.00,
    10,
    10,
    3,
    NULL,
    1,
    0,
    1,
    'RENTAL',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-FREE')
  ),
  (
    'ITM-BND-001',
    'Paket Wedding Lengkap',
    (SELECT id FROM categories WHERE name = 'Paket / Bundling'),
    'Paket lengkap gaun, jas, dan dekorasi untuk sesi foto wedding.',
    0.00,
    0.00,
    3800.00,
    3800.00,
    2,
    2,
    1,
    NULL,
    0,
    1,
    1,
    'SALE',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-FREE')
  ),
  (
    'ITM-PRP-001',
    'Backdrop Bunga Garden',
    (SELECT id FROM categories WHERE name = 'Dekorasi / Properti'),
    'Backdrop bunga artifisial untuk dekorasi pelaminan indoor.',
    210.00,
    75.00,
    0.00,
    75.00,
    4,
    4,
    2,
    NULL,
    1,
    0,
    1,
    'RENTAL',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-FREE')
  ),
  (
    'ITM-NEW-001',
    'Gaun Koleksi 2025',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    'Gaun daily couture koleksi 2025 untuk pembelian langsung.',
    520.00,
    0.00,
    1250.00,
    1250.00,
    6,
    6,
    2,
    NULL,
    0,
    1,
    1,
    'SALE',
    'AVAILABLE',
    (SELECT id FROM item_sizes WHERE code = 'SIZE-M')
  );
