-- ============================================
-- Seeder: Items (SQLite Compatible)
-- ============================================

-- Reset items so the new data always seeds clean
DELETE FROM items;

-- Insert sample items for rental business
-- Note: stock_quantity and available_quantity are set to 0 by default (managed through stock movements)
INSERT INTO items (
    code,
    name,
    category_id,
    size_id,
    description,
    purchase_price,
    rental_price_per_day,
    sale_price,
    price,
    deposit,
    type,
    status,
    stock_quantity,
    available_quantity,
    min_stock_alert,
    is_available_for_rent,
    is_available_for_sale,
    is_active,
    discount_group_id,
    created_at,
    updated_at
) VALUES
-- Pakaian Adat
(
    'RENT001',
    'Kebaya Jawa Putih',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Kebaya tradisional Jawa dengan warna putih, cocok untuk acara adat dan pernikahan tradisional.',
    350000.00,
    50000.00,
    0.00,
    50000.00,
    100000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT002',
    'Baju Bodo Sulawesi',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Baju Bodo tradisional Sulawesi Selatan dengan warna merah cerah.',
    450000.00,
    60000.00,
    0.00,
    60000.00,
    120000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT003',
    'Kebaya Bali Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Kebaya Bali dengan motif modern, kombinasi warna emas dan merah.',
    400000.00,
    55000.00,
    0.00,
    55000.00,
    110000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT004',
    'Baju Batik Papua',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    (SELECT id FROM item_sizes WHERE code = 'XL'),
    'Baju batik khas Papua dengan motif khas daerah.',
    380000.00,
    50000.00,
    0.00,
    50000.00,
    100000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Pakaian Pernikahan
(
    'RENT005',
    'Gaun Pengantin Putih',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Gaun pengantin warna putih dengan payet dan renda elegan.',
    2500000.00,
    750000.00,
    0.00,
    750000.00,
    1500000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT006',
    'Kebaya Pengantin Emas',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Kebaya pengantin dengan payet emas dan brokat mewah.',
    1800000.00,
    600000.00,
    0.00,
    600000.00,
    1200000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT007',
    'Jas Pengantin Hitam',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Jas pengantin hitam formal dengan dasi kupu-kupu.',
    1200000.00,
    400000.00,
    0.00,
    400000.00,
    800000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT008',
    'Gaun Pengantin Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Gaun pengantin modern dengan desain simple dan elegan.',
    2200000.00,
    700000.00,
    0.00,
    700000.00,
    1400000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Pakaian Acara / Formal
(
    'RENT009',
    'Gaun Wisuda Biru Navy',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Gaun wisuda warna biru navy dengan model klasik.',
    800000.00,
    200000.00,
    0.00,
    200000.00,
    400000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT010',
    'Dress Pesta Hitam',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Dress pesta hitam dengan model elegan cocok untuk acara formal.',
    650000.00,
    150000.00,
    0.00,
    150000.00,
    300000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT011',
    'Batik Formal Coklat',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    (SELECT id FROM item_sizes WHERE code = 'XL'),
    'Batik formal dengan motif klasik warna coklat, cocok untuk acara resmi.',
    500000.00,
    100000.00,
    0.00,
    100000.00,
    200000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Pakaian Anak-anak
(
    'RENT012',
    'Kostum Princess Anak',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Kostum princess lengkap dengan tiara untuk anak-anak.',
    300000.00,
    75000.00,
    0.00,
    75000.00,
    150000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT013',
    'Kostum Superhero Anak',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak'),
    (SELECT id FROM item_sizes WHERE code = 'ONE-SIZE'),
    'Kostum superhero lengkap dengan cape untuk anak laki-laki.',
    250000.00,
    60000.00,
    0.00,
    60000.00,
    120000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Pakaian Casual / Modern
(
    'RENT014',
    'Dress Kekinian Floral',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Dress modern dengan motif floral, cocok untuk photoshoot atau casual.',
    350000.00,
    80000.00,
    0.00,
    80000.00,
    160000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'RENT015',
    'Batik Modern Warna Pastel',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Batik modern dengan warna pastel, desain kekinian.',
    400000.00,
    90000.00,
    0.00,
    90000.00,
    180000.00,
    'RENTAL',
    'AVAILABLE',
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Item Penjualan
(
    'ITM001',
    'Batik Modern Ready Stock',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Batik modern ready stock, cocok untuk dijual langsung.',
    150000.00,
    0.00,
    250000.00,
    250000.00,
    0.00,
    'SALE',
    'AVAILABLE',
    0,
    0,
    5,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ITM002',
    'Dress Kekinian New Arrival',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Dress kekinian new arrival, produk baru untuk dijual.',
    180000.00,
    0.00,
    300000.00,
    300000.00,
    0.00,
    'SALE',
    'AVAILABLE',
    0,
    0,
    5,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ITM003',
    'Kemeja Batik Premium',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    (SELECT id FROM item_sizes WHERE code = 'XL'),
    'Kemeja batik premium dengan kualitas terbaik untuk dijual.',
    200000.00,
    0.00,
    350000.00,
    350000.00,
    0.00,
    'SALE',
    'AVAILABLE',
    0,
    0,
    5,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ITM004',
    'Kostum Party Anak Premium',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Kostum party anak premium, baru untuk dijual.',
    120000.00,
    0.00,
    200000.00,
    200000.00,
    0.00,
    'SALE',
    'AVAILABLE',
    0,
    0,
    5,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ITM005',
    'Baju Casual Modern Collection',
    (SELECT id FROM categories WHERE name = 'Penjualan Item Baru'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Baju casual modern collection, produk baru untuk dijual.',
    175000.00,
    0.00,
    280000.00,
    280000.00,
    0.00,
    'SALE',
    'AVAILABLE',
    0,
    0,
    5,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);


