-- ============================================
-- Seeder: Accessories (SQLite Compatible)
-- ============================================

-- Reset accessories so the new data always seeds clean
DELETE FROM accessories;

-- Insert sample accessories for rental business
-- Note: stock_quantity and available_quantity are set to 0 by default (managed through stock movements)
INSERT INTO accessories (
    code,
    name,
    description,
    purchase_price,
    rental_price_per_day,
    sale_price,
    stock_quantity,
    available_quantity,
    min_stock_alert,
    is_available_for_rent,
    is_available_for_sale,
    is_active,
    discount_group_id,
    created_at,
    updated_at
) VALUES
-- Mahkota dan Tiara
(
    'ACC001',
    'Mahkota Pengantin Emas',
    'Mahkota pengantin dengan payet emas dan kristal, sangat elegan.',
    850000.00,
    150000.00,
    0.00,
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC002',
    'Tiara Princess',
    'Tiara princess dengan batu kristal, cocok untuk anak-anak atau pesta tema.',
    200000.00,
    30000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC003',
    'Siger Lampung',
    'Siger tradisional Lampung dengan hiasan emas dan manik-manik.',
    600000.00,
    100000.00,
    0.00,
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Kalung dan Perhiasan
(
    'ACC004',
    'Kalung Mutiara Putih',
    'Kalung mutiara putih panjang, cocok untuk gaun formal dan pernikahan.',
    450000.00,
    75000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC005',
    'Kalung Emas Antik',
    'Kalung emas dengan desain antik, cocok untuk kebaya tradisional.',
    1200000.00,
    200000.00,
    0.00,
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC006',
    'Gelang Emas',
    'Gelang emas dengan ukiran tradisional.',
    350000.00,
    50000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC007',
    'Anting Emas Bulat',
    'Anting emas dengan batu bulat, cocok untuk berbagai acara formal.',
    250000.00,
    40000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Sepatu
(
    'ACC008',
    'Sepatu High Heels Putih',
    'Sepatu high heels putih untuk pengantin atau acara formal.',
    500000.00,
    80000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC009',
    'Sepatu Flats Emas',
    'Sepatu flats warna emas, nyaman untuk acara panjang.',
    300000.00,
    50000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC010',
    'Sandals Wanita Emas',
    'Sandals wanita dengan hiasan emas, elegan dan nyaman.',
    200000.00,
    35000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC011',
    'Sepatu Pantofel Hitam',
    'Sepatu pantofel hitam formal untuk pria.',
    400000.00,
    60000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Selendang dan Kain
(
    'ACC012',
    'Selendang Sutra Merah',
    'Selendang sutra warna merah, cocok untuk kebaya.',
    150000.00,
    25000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC013',
    'Selendang Batik',
    'Selendang batik dengan motif klasik.',
    120000.00,
    20000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC014',
    'Kain Songket Emas',
    'Kain songket dengan benang emas, untuk acara adat.',
    800000.00,
    150000.00,
    0.00,
    0,
    0,
    2,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- Aksesoris Tambahan
(
    'ACC015',
    'Tas Clutch Emas',
    'Tas clutch warna emas, cocok untuk pesta atau pernikahan.',
    250000.00,
    40000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC016',
    'Dasi Kupu-kupu Hitam',
    'Dasi kupu-kupu hitam untuk jas formal pria.',
    75000.00,
    15000.00,
    0.00,
    0,
    0,
    5,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC017',
    'Sanggul Pengantin',
    'Sanggul pengantin dengan hiasan bunga dan payet.',
    300000.00,
    50000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC018',
    'Kerudung Modern',
    'Kerudung modern dengan warna matching, untuk hijab style.',
    100000.00,
    20000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC019',
    'Tasbih Mutiara',
    'Tasbih mutiara untuk pelengkap busana muslim.',
    150000.00,
    25000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ACC020',
    'Bros Emas',
    'Bros emas dengan ukiran tradisional, untuk hiasan kebaya.',
    180000.00,
    30000.00,
    0.00,
    0,
    0,
    3,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);


