-- ============================================
-- Seeder: Items (SQLite Compatible)
-- ============================================

-- Reset items so the new data seeds clean
DELETE FROM items;

-- Insert curated item master data with stock and discount links
INSERT INTO items (
  code,
  name,
  category_id,
  size_id,
  description,
  purchase_price,
  rental_price_per_day,
  sale_price,
  deposit,
  type,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  image_path,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  discount_group_id,
  created_at,
  updated_at
) VALUES
  (
    'ITM001',
    'Kebaya Klasik Jawa',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Kebaya sulam tangan dengan sentuhan detail emas untuk pengantin tradisional Jawa.',
    350000,
    95000,
    750000,
    200000,
    'RENTAL',
    5,
    5,
    1,
    'images/items/kebaya-jawa.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'E'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM002',
    'Set Baju Adat Bali',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Set baju adat Bali lengkap dengan kain dan udeng yang autenrik.',
    420000,
    110000,
    850000,
    250000,
    'RENTAL',
    3,
    3,
    1,
    'images/items/set-adat-bali.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'B'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM003',
    'Gaun Formal Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Gaun satin mutiara dengan potongan A-line untuk acara wisuda atau pesta malam.',
    280000,
    72000,
    600000,
    150000,
    'RENTAL',
    6,
    5,
    2,
    'images/items/gaun-formal.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'A'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM004',
    'Kostum Anak Putri',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak'),
    (SELECT id FROM item_sizes WHERE code = 'XS'),
    'Kostum putri modern lengkap dengan bordir dan cape untuk pemotretan keluarga.',
    180000,
    42000,
    300000,
    50000,
    'RENTAL',
    4,
    4,
    1,
    'images/items/kostum-anak.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'H'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM005',
    'Dress Casual Batik',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern'),
    (SELECT id FROM item_sizes WHERE code = 'M'),
    'Dress kasual motif batik kontemporer untuk sesi event dan gaya sehari-hari.',
    220000,
    62000,
    500000,
    100000,
    'RENTAL',
    7,
    7,
    2,
    'images/items/dress-batik.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'C'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM006',
    'Properti Dekorasi Fotobooth',
    (SELECT id FROM categories WHERE name = 'Dekorasi / Properti'),
    NULL,
    'Rangkaian properti photobooth dengan tirai satin, lampu, dan rak bunga.',
    500000,
    120000,
    1200000,
    0,
    'BOTH',
    2,
    2,
    1,
    'images/items/dekorasi-fotobooth.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'D'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM007',
    'Peralatan Pendukung Serbaguna',
    (SELECT id FROM categories WHERE name = 'Peralatan Pendukung'),
    NULL,
    'Set hanger, cover, dan kotak transportasi untuk mengorganisir barang selama rental.',
    80000,
    25000,
    160000,
    0,
    'BOTH',
    10,
    10,
    3,
    'images/items/peralatan-pendukung.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'F'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM008',
    'Set Jas Modern',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal'),
    (SELECT id FROM item_sizes WHERE code = 'L'),
    'Set jas modern dengan potongan slim-fit untuk momen bisnis formal atau event resmi.',
    460000,
    135000,
    980000,
    250000,
    'RENTAL',
    4,
    4,
    2,
    'images/items/jas-modern.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'D'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM009',
    'Kostum Anak Laki',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak'),
    (SELECT id FROM item_sizes WHERE code = 'S'),
    'Setelan anak laki-laki dengan rompi dan topi untuk tema pesta keluarga.',
    95000,
    28000,
    210000,
    40000,
    'RENTAL',
    6,
    6,
    2,
    'images/items/kostum-anak-laki.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'I'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM010',
    'Set Dekorasi Elegan',
    (SELECT id FROM categories WHERE name = 'Dekorasi / Properti'),
    NULL,
    'Paket dekorasi meja dengan bunga, tirai, dan lampion custom warna emas.',
    270000,
    60000,
    650000,
    0,
    'BOTH',
    5,
    5,
    1,
    'images/items/dekorasi-meja.jpg',
    1,
    1,
    1,
    (SELECT id FROM discount_groups WHERE code = 'J'),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
