-- ============================================
-- Seeder: Items / Katalog Barang (SQLite Compatible)
-- ============================================

-- Reset items so the new data always seeds clean
DELETE FROM items;

-- Insert default items
INSERT INTO items (
  code,
  name,
  description,
  category_id,
  size_id,
  purchase_price,
  rental_price_per_day,
  sale_price,
  price,
  type,
  status,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  discount_group_id,
  created_at,
  updated_at
) VALUES
  -- Pakaian Adat
  (
    'ITM001',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM002',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM003',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM004',
    'Baju Adat Bali',
    'Baju adat Bali lengkap dengan aksesoris tradisional',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    400000.00,
    85000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM005',
    'Baju Adat Bali',
    'Baju adat Bali lengkap dengan aksesoris tradisional',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    400000.00,
    85000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM006',
    'Baju Adat Kalimantan',
    'Baju adat Dayak Kalimantan dengan motif khas',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    450000.00,
    90000.00,
    600000.00,
    600000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM007',
    'Baju Adat Kalimantan',
    'Baju adat Dayak Kalimantan dengan motif khas',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    450000.00,
    90000.00,
    600000.00,
    600000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM008',
    'Baju Adat Sumatera',
    'Baju adat tradisional Sumatera dengan warna cerah',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    380000.00,
    80000.00,
    520000.00,
    520000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM009',
    'Baju Adat Sumatera',
    'Baju adat tradisional Sumatera dengan warna cerah',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    380000.00,
    80000.00,
    520000.00,
    520000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM010',
    'Baju Adat Papua',
    'Baju adat Papua dengan hiasan bulu dan manik-manik',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    500000.00,
    100000.00,
    650000.00,
    650000.00,
    'RENTAL',
    'AVAILABLE',
    1,
    1,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Pakaian Pernikahan
  (
    'ITM011',
    'Gaun Pengantin Putih',
    'Gaun pengantin putih modern dengan train panjang',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    2500000.00,
    500000.00,
    3500000.00,
    3500000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM012',
    'Gaun Pengantin Putih',
    'Gaun pengantin putih modern dengan train panjang',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    2500000.00,
    500000.00,
    3500000.00,
    3500000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM013',
    'Kebaya Pengantin',
    'Kebaya pengantin dengan payet dan bordir mewah',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    1800000.00,
    400000.00,
    2500000.00,
    2500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM014',
    'Kebaya Pengantin',
    'Kebaya pengantin dengan payet dan bordir mewah',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    1800000.00,
    400000.00,
    2500000.00,
    2500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM015',
    'Jas Pengantin',
    'Jas pengantin pria dengan setelan lengkap',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    1500000.00,
    350000.00,
    2200000.00,
    2200000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM016',
    'Jas Pengantin',
    'Jas pengantin pria dengan setelan lengkap',
    (SELECT id FROM categories WHERE name = 'Pakaian Pernikahan' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    1500000.00,
    350000.00,
    2200000.00,
    2200000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Pakaian Acara / Formal
  (
    'ITM017',
    'Dress Wisuda',
    'Dress formal untuk wisuda dengan warna elegan',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    300000.00,
    60000.00,
    450000.00,
    450000.00,
    'RENTAL',
    'AVAILABLE',
    5,
    5,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM018',
    'Dress Wisuda',
    'Dress formal untuk wisuda dengan warna elegan',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    300000.00,
    60000.00,
    450000.00,
    450000.00,
    'RENTAL',
    'AVAILABLE',
    5,
    5,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM019',
    'Dress Pesta',
    'Dress pesta dengan model modern dan warna menarik',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    250000.00,
    50000.00,
    380000.00,
    380000.00,
    'RENTAL',
    'AVAILABLE',
    6,
    6,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM020',
    'Dress Pesta',
    'Dress pesta dengan model modern dan warna menarik',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    250000.00,
    50000.00,
    380000.00,
    380000.00,
    'RENTAL',
    'AVAILABLE',
    6,
    6,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM021',
    'Dress Ulang Tahun',
    'Dress untuk acara ulang tahun dengan motif lucu',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'S' LIMIT 1),
    200000.00,
    40000.00,
    300000.00,
    300000.00,
    'RENTAL',
    'AVAILABLE',
    8,
    8,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM022',
    'Dress Ulang Tahun',
    'Dress untuk acara ulang tahun dengan motif lucu',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    200000.00,
    40000.00,
    300000.00,
    300000.00,
    'RENTAL',
    'AVAILABLE',
    8,
    8,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM023',
    'Setelan Jas Formal',
    'Setelan jas formal untuk pria, cocok untuk acara resmi',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    400000.00,
    80000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    4,
    4,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM024',
    'Setelan Jas Formal',
    'Setelan jas formal untuk pria, cocok untuk acara resmi',
    (SELECT id FROM categories WHERE name = 'Pakaian Acara / Formal' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    400000.00,
    80000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Pakaian Anak-anak
  (
    'ITM025',
    'Kostum Princess',
    'Kostum princess untuk anak perempuan',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'S' LIMIT 1),
    150000.00,
    30000.00,
    220000.00,
    220000.00,
    'RENTAL',
    'AVAILABLE',
    10,
    10,
    3,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM026',
    'Kostum Superhero',
    'Kostum superhero untuk anak laki-laki',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'S' LIMIT 1),
    120000.00,
    25000.00,
    180000.00,
    180000.00,
    'RENTAL',
    'AVAILABLE',
    10,
    10,
    3,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM027',
    'Baju Adat Anak',
    'Baju adat untuk anak-anak dengan ukuran kecil',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XS' LIMIT 1),
    180000.00,
    35000.00,
    250000.00,
    250000.00,
    'RENTAL',
    'AVAILABLE',
    8,
    8,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM028',
    'Baju Adat Anak',
    'Baju adat untuk anak-anak dengan ukuran kecil',
    (SELECT id FROM categories WHERE name = 'Pakaian Anak-anak' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'S' LIMIT 1),
    180000.00,
    35000.00,
    250000.00,
    250000.00,
    'RENTAL',
    'AVAILABLE',
    8,
    8,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Pakaian Casual / Modern
  (
    'ITM029',
    'Dress Modern Kekinian',
    'Dress modern dengan model terbaru untuk photoshoot',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    200000.00,
    40000.00,
    300000.00,
    300000.00,
    'RENTAL',
    'AVAILABLE',
    7,
    7,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM030',
    'Dress Modern Kekinian',
    'Dress modern dengan model terbaru untuk photoshoot',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    200000.00,
    40000.00,
    300000.00,
    300000.00,
    'RENTAL',
    'AVAILABLE',
    7,
    7,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM031',
    'Batik Modern',
    'Batik modern dengan motif kontemporer',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    180000.00,
    35000.00,
    260000.00,
    260000.00,
    'RENTAL',
    'AVAILABLE',
    6,
    6,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM032',
    'Batik Modern',
    'Batik modern dengan motif kontemporer',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    180000.00,
    35000.00,
    260000.00,
    260000.00,
    'RENTAL',
    'AVAILABLE',
    6,
    6,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM033',
    'Batik Modern',
    'Batik modern dengan motif kontemporer',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    180000.00,
    35000.00,
    260000.00,
    260000.00,
    'RENTAL',
    'AVAILABLE',
    5,
    5,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM034',
    'Kemeja Batik Pria',
    'Kemeja batik modern untuk pria',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    150000.00,
    30000.00,
    220000.00,
    220000.00,
    'RENTAL',
    'AVAILABLE',
    8,
    8,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM035',
    'Kemeja Batik Pria',
    'Kemeja batik modern untuk pria',
    (SELECT id FROM categories WHERE name = 'Pakaian Casual / Modern' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    150000.00,
    30000.00,
    220000.00,
    220000.00,
    'RENTAL',
    'AVAILABLE',
    6,
    6,
    2,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );

