-- ============================================
-- Seeder: Items / Katalog Barang (SQLite Compatible)
-- ============================================

-- Reset items so the new data always seeds clean
DELETE FROM items;

-- Insert default items
INSERT INTO items (
  code,
  name,
  description,
  category_id,
  size_id,
  purchase_price,
  rental_price_per_day,
  sale_price,
  price,
  type,
  status,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  discount_group_id,
  created_at,
  updated_at
) VALUES
  -- Pakaian Adat
  (
    'ITM001',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM002',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM003',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM004',
    'Baju Adat Bali',
    'Baju adat Bali lengkap dengan aksesoris tradisional',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    400000.00,
    85000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM005',
    'Baju Adat Bali',
    'Baju adat Bali lengkap dengan aksesoris tradisional',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    400000.00,
    85000.00,
    550000.00,
    550000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM006',
    'Baju Adat Kalimantan',
    'Baju adat Dayak Kalimantan dengan motif khas',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    450000.00,
    90000.00,
    600000.00,
    600000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'ITM007',
    'Baju Adat Kalimantan',
    'Baju adat Dayak Kalimantan dengan motif khas',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    450000.00,
    90000.00,
    600000.00,
    600000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );