-- ============================================ 
-- Seeder: Items / Katalog Barang (SQLite Compatible)
-- ============================================

-- Reset items so the new data always seeds clean
DELETE FROM items;

-- Insert default items
INSERT INTO items (
  code,
  name,
  description,
  category_id,
  size_id,
  purchase_price,
  rental_price_per_day,
  sale_price,
  price,
  type,
  status,
  stock_quantity,
  available_quantity,
  min_stock_alert,
  is_available_for_rent,
  is_available_for_sale,
  is_active,
  discount_group_id,
  created_at,
  updated_at
) VALUES
  -- ============================================
  -- 3 ITEM TIPE SALE (Hanya untuk dijual)
  -- ============================================
  (
    'SALE001',
    'Kemeja Batik Premium',
    'Kemeja batik premium dengan kualitas tinggi, cocok untuk acara formal dan bisnis',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    250000.00,
    0.00,
    450000.00,
    400000.00,
    'SALE',
    'AVAILABLE',
    5,
    5,
    2,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'SALE002',
    'Sarung Tenun Ikat',
    'Sarung tenun ikat tradisional dengan motif khas Nusantara, bahan premium',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    180000.00,
    0.00,
    320000.00,
    300000.00,
    'SALE',
    'AVAILABLE',
    8,
    8,
    2,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'SALE003',
    'Selendang Songket',
    'Selendang songket dengan benang emas, cocok untuk pelengkap pakaian adat',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    120000.00,
    0.00,
    220000.00,
    200000.00,
    'SALE',
    'AVAILABLE',
    10,
    10,
    3,
    0,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- ============================================
  -- 3 ITEM TIPE BOTH (Bisa disewa dan dijual)
  -- ============================================
  (
    'BOTH001',
    'Kebaya Jawa Modern',
    'Kebaya Jawa modern dengan motif batik halus, cocok untuk acara adat dan formal',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    350000.00,
    75000.00,
    500000.00,
    500000.00,
    'BOTH',
    'AVAILABLE',
    4,
    4,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'BOTH002',
    'Baju Adat Bali',
    'Baju adat Bali lengkap dengan aksesoris tradisional, bisa disewa atau dibeli',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    400000.00,
    85000.00,
    550000.00,
    550000.00,
    'BOTH',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'BOTH003',
    'Baju Adat Kalimantan',
    'Baju adat Dayak Kalimantan dengan motif khas, tersedia untuk sewa atau beli',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    450000.00,
    90000.00,
    600000.00,
    600000.00,
    'BOTH',
    'AVAILABLE',
    3,
    3,
    1,
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- ============================================
  -- 3 ITEM TIPE RENTAL (Hanya untuk disewa)
  -- ============================================
  (
    'RENT001',
    'Kebaya Encim Betawi',
    'Kebaya encim khas Betawi dengan aksesoris lengkap, khusus untuk disewa',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'M' LIMIT 1),
    500000.00,
    100000.00,
    0.00,
    700000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'RENT002',
    'Baju Adat Minangkabau',
    'Baju adat Minangkabau lengkap dengan hiasan emas, khusus untuk acara adat',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'L' LIMIT 1),
    600000.00,
    120000.00,
    0.00,
    800000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'RENT003',
    'Kebaya Jawa Klasik',
    'Kebaya Jawa klasik dengan detail bordir halus, cocok untuk pernikahan adat',
    (SELECT id FROM categories WHERE name = 'Pakaian Adat' LIMIT 1),
    (SELECT id FROM item_sizes WHERE code = 'XL' LIMIT 1),
    550000.00,
    110000.00,
    0.00,
    750000.00,
    'RENTAL',
    'AVAILABLE',
    2,
    2,
    1,
    1,
    0,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );







